[package]
name = "rocket-mem-test"
version = "0.1.0"
authors = ["Fuyang Liu <liufuyang@users.noreply.github.com>"]

[dependencies]
rocket = "0.3.17"
rocket_codegen = "0.3.17"
rocket_contrib = "0.3.17"